### PR TITLE
Feat/function simple search

### LINKED ISSUE #13: Function simple search
### D.2 

Here we should make a simple search function. This should be found via the title/plot description

This function should be called `string_search()`
For the movies found return id and title

### PR DESCRIPTION
**Pull request by MarLaslo**
simple_search()

It should be working, and the issue is probably completed.

### CODE REVIEW

**Comment by MarLaslo** [comment]
#13

**Comment by MarLaslo** [comment]
OK so I think I figured out where I did a mistake with branching.

I did a branch from my other branch and not from main.
So if I am correct it is enough to merge this one.

Is my assumption correct? I am just getting hang of git

**Comment by sofushn** [comment]
> I did a branch from my other branch and not from main. So if I am correct it is enough to merge this one.

There will likely be some conflicts because both PR's makes the same changes to  `omdb_data_merge.sql` and `B2_build_movie_db.sql`. The simplest way to fix this is to create a new branch from `main` and then cherry pick the commit you made to this branch like this:

Create a new feature branch from main
```
git switch -c feature/new-branch main
```

While in the newly created feature branch, use git cherry-pick to pick the commits from the old, merged branch to merge them into the new feature branch.

```
git cherry-pick <commit1> <commit2> <...> <...>
```

Finish by pushing your feature branch, now including your commits, to remote:
```
git push -u origin feature/new-branch
```

**Comment by MarLaslo** [comment]
I think simpler can be if I just remove the other pull request and use this one as it has all the changes.

**Pull request closed without merging**
